In [10]:
# Import our dependencies

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
#import tensorflow as tf

#  Import and read the WELFake_Dataset.csv.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
news_df = pd.read_csv("WELFake_Dataset.csv")
news_df.head(20)

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
5,5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1
6,6,DR BEN CARSON TARGETED BY THE IRS: “I never ha...,DR. BEN CARSON TELLS THE STORY OF WHAT HAPPENE...,1
7,7,HOUSE INTEL CHAIR On Trump-Russia Fake Story: ...,,1
8,8,Sports Bar Owner Bans NFL Games…Will Show Only...,"The owner of the Ringling Bar, located south o...",1
9,9,Latest Pipeline Leak Underscores Dangers Of Da...,"FILE – In this Sept. 15, 2005 file photo, the ...",1
10,10,GOP Senator Just Smacked Down The Most Puncha...,The most punchable Alt-Right Nazi on the inter...,1
11,11,"May Brexit offer would hurt, cost EU citizens ...",BRUSSELS (Reuters) - British Prime Minister Th...,0
12,12,Schumer calls on Trump to appoint official to ...,"WASHINGTON (Reuters) - Charles Schumer, the to...",0
13,13,WATCH: HILARIOUS AD Calls Into Question Health...,"After watching this telling video, you ll wond...",1
14,14,No Change Expected for ESPN Political Agenda D...,As more and more sports fans turn off ESPN to ...,0
15,15,Billionaire Odebrecht in Brazil scandal releas...,RIO DE JANEIRO/SAO PAULO (Reuters) - Billionai...,0
16,16,BRITISH WOMAN LOSES VIRGINITY To Asylum Seekin...,Europe is likely not going to be a top destina...,1
17,17,U.N. seeks humanitarian pause in Sanaa where s...,GENEVA (Reuters) - The United Nations called o...,0
18,18,MAJOR LIBERAL RAG RELUCTANTLY PUBLISHES Articl...,"The Atlantic, a publication that wouldn t know...",1
19,19,Second judge says Clinton email setup may have...,NEW YORK (Reuters) - A second federal judge ha...,0

## Pyspark can not read pandas file correctly cause of Enteres & tabs in the text

In [11]:
# Drop Unnecessary Columns
news_df=news_df.drop("Unnamed: 0", axis=1)
news_df

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,NaN,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...
72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [12]:
# Get rid of enters, - _ ect
news_df.replace(r'\n','', regex=True, inplace=True) 
news_df.replace(r'\r','', regex=True, inplace=True) 
news_df.replace(r'\t','', regex=True, inplace=True)

In [13]:
news_df.replace(r'^\s*$', np.nan, regex=True, inplace = True)

In [14]:
news_df = news_df.fillna("ghgg")

In [15]:
news_df.head(10)

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,ghgg,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1
6,DR BEN CARSON TARGETED BY THE IRS: “I never ha...,DR. BEN CARSON TELLS THE STORY OF WHAT HAPPENE...,1
7,HOUSE INTEL CHAIR On Trump-Russia Fake Story: ...,ghgg,1
8,Sports Bar Owner Bans NFL Games…Will Show Only...,"The owner of the Ringling Bar, located south o...",1
9,Latest Pipeline Leak Underscores Dangers Of Da...,"FILE – In this Sept. 15, 2005 file photo, the ...",1

In [16]:


trump = news_df[news_df['text'].str.contains("trump", regex=True, case = False)]

trump['label'].value_counts()
trump

,title,text,label
10,GOP Senator Just Smacked Down The Most Puncha...,The most punchable Alt-Right Nazi on the inter...,1
12,Schumer calls on Trump to appoint official to ...,"WASHINGTON (Reuters) - Charles Schumer, the to...",0
14,No Change Expected for ESPN Political Agenda D...,As more and more sports fans turn off ESPN to ...,0
18,MAJOR LIBERAL RAG RELUCTANTLY PUBLISHES Articl...,"The Atlantic, a publication that wouldn t know...",1
22,"Sean Spicer Baffles Reporters, Claims Trump I...","On Tuesday, White House Propaganda Minister Se...",1
...,...,...,...
72124,An Unlikely Contender Rises in France as the A...,"PARIS — In the age of Donald J. Trump, “Bre...",0
72128,JUDGE JEANINE SOUNDS FREE SPEECH ALARM: “They ...,Judge Jeanine lets it rip! She s concerned wit...,1
72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0

In [17]:
# word_count = pd.DataFrame(news_df["text"].str.split(expand=True).stack().value_counts()[:5])
# word_count.reset_index(inplace=True)
# word_count.rename(columns = {'index':'Words', '0':'count'}, inplace = True)
# word_count.columns = ["Words", "Count"]

In [18]:
word_count
word_count_test = word_count

NameError: name 'word_count' is not defined

In [ ]:
word_count

In [ ]:
words_list = word_count["Words"]

In [ ]:
count = word_df['label'].value_counts()
count

In [ ]:
# def counting(word_list, data):
#     temp = pd.DataFrame(columns=['word'])
#     for word in word_list:
#         word_df = data[data['text'].str.contains(word, regex=True, case = False)]
#         count = data['label'].value_counts(sort = False)
#         temp = temp.append({'word': word, '1_count':count[1], "0_count": count[0], "total" : count[1] + count[0]}, ignore_index=True)
#         return temp

In [ ]:
counting(["car"],news_df)

In [ ]:
word_count_test

In [ ]:
df["text"].str.contains

In [19]:
news_df.to_csv('fake.csv',sep = '\t')

In [ ]:
# Count label values
pd.DataFrame(news_df['label'].value_counts()).T

In [ ]:
# Counting with plot both labels
sns.countplot(x="label", data=news_df)

In [ ]:
news_df.dtypes

In [ ]:
from pyspark.ml.feature import Tokenizer
from pyspark.sql import SparkSession
import findspark
findspark.init()

In [ ]:
spark = SparkSession.builder.appName("Tokens").getOrCreate()

In [ ]:
news_spark = spark.read.csv("fake.csv",sep ='\t', header = True)

In [ ]:
news_spark.show(50)